"""Conversation memory -- rolling summarization for long-term chat context."""

import json
import time
from datetime import datetime, timezone
from uuid import UUID

import structlog

from langchain_core.messages import HumanMessage, SystemMessage
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.chat_message import ChatMessage
from app.prompts import CONVERSATION_SUMMARY_HUMAN, CONVERSATION_SUMMARY_SYSTEM
from app.schemas.llm_outputs import ConversationSummaryData
from app.services.llm import safe_llm_invoke
from app.utils.db import db_error_guard
from app.utils.sanitizer import sanitize_chat_message
from app.utils.token_budget import TokenBudget
from app.utils.limits import CONVERSATION_MEMORY_LIMIT

logger = structlog.get_logger('read-pal.memory')

# When to trigger summarization
SUMMARY_THRESHOLD = 30  # summarize when more than this many messages exist
SUMMARY_BATCH = 15       # compress oldest N messages into summary
MAX_RECENT = 20          # keep this many recent messages verbatim

# P3.1: Bump when the ConversationSummary JSON shape gains/loses fields or
# semantics change. Stored alongside the prompt_version so we can detect
# "shape-mismatch" rows separately from "prompt-template-mismatch" rows.
MEMORY_SCHEMA_VERSION = 1


def _build_summary_metadata(model_name: str | None) -> dict:
    """Build the provenance metadata block for a freshly generated summary.

    Captures prompt_version + schema_version + model + timestamp so future
    reads can detect stale rows (prompt/schema drift) and regenerate instead
    of trusting outdated summaries. Model name is best-effort because the
    underlying router may fall back across providers; observability is the
    goal, not enforcement.
    """
    return {
        'prompt_version': CONVERSATION_SUMMARY_SYSTEM.version,
        'schema_version': MEMORY_SCHEMA_VERSION,
        'model': model_name or 'unknown',
        'generated_at': datetime.now(tz=timezone.utc).isoformat(),
    }


def _is_summary_stale(existing: 'ConversationSummary | None') -> bool:
    """Return True if ``existing`` was generated by an outdated prompt.

    Treats NULL metadata as stale (pre-P3.1 rows, or rows written by older
    code) so they get refreshed on next access rather than trusted blindly.
    """
    if existing is None:
        return True
    meta = getattr(existing, 'metadata_', None) or {}
    if not isinstance(meta, dict):
        return True
    if meta.get('prompt_version') != CONVERSATION_SUMMARY_SYSTEM.version:
        return True
    if meta.get('schema_version') != MEMORY_SCHEMA_VERSION:
        return True
    return False


async def _count_messages(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
) -> int:
    """Count total chat messages for a user-book pair."""
    async with db_error_guard('_count_messages', user_id=str(user_id), book_id=str(book_id)):
        count_result = await db.execute(
            select(func.count(ChatMessage.id)).where(
                ChatMessage.user_id == user_id,
                ChatMessage.book_id == book_id,
                ChatMessage.deleted_at.is_(None),
            )
        )
        return count_result.scalar() or 0


async def _load_existing_summary(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
) -> 'ConversationSummary | None':
    """Load the most recent conversation summary from the database."""
    from app.models.conversation_summary import ConversationSummary
    async with db_error_guard('_load_existing_summary', user_id=str(user_id), book_id=str(book_id)):
        result = await db.execute(
            select(ConversationSummary)
            .where(
                ConversationSummary.user_id == user_id,
                ConversationSummary.book_id == book_id,
            )
            .order_by(ConversationSummary.updated_at.desc())
            .limit(1)
        )
        return result.scalar_one_or_none()


def _log_summary_result(
    event: str,
    total: int,
    summary_length: int,
    latency_ms: int,
    user_id: UUID,
    book_id: UUID,
) -> None:
    """Log the outcome of a summary lookup or generation."""
    logger.info(
        event,
        message_count=total,
        summary_length=summary_length,
        latency_ms=latency_ms,
        user_id=str(user_id),
        book_id=str(book_id),
    )


async def get_or_create_summary(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
) -> str | None:
    """Get existing summary, or create one if threshold is met.

    Returns the summary text or None if no summary exists/is needed.
    """
    t0 = time.monotonic()
    logger.info(
        'memory.get_or_create_summary.started',
        user_id=str(user_id),
        book_id=str(book_id),
    )

    total = await _count_messages(db, user_id, book_id)
    if total < SUMMARY_THRESHOLD:
        logger.info(
            'memory.get_or_create_summary.below_threshold',
            message_count=total,
            threshold=SUMMARY_THRESHOLD,
            user_id=str(user_id),
            book_id=str(book_id),
        )
        return None

    existing = await _load_existing_summary(db, user_id, book_id)

    # P3.1: cache hit requires BOTH (a) message-count is still fresh enough
    # AND (b) the stored summary was generated by the current prompt/schema
    # version. A stale-version row is force-regenerated even if its
    # message_count looks current — otherwise prompt improvements never
    # backfill to historical summaries.
    if (
        existing
        and not _is_summary_stale(existing)
        and existing.message_count >= total - MAX_RECENT
    ):
        elapsed = int((time.monotonic() - t0) * 1000)
        _log_summary_result(
            'memory.get_or_create_summary.cache_hit',
            total, len(existing.summary), elapsed, user_id, book_id,
        )
        return existing.summary

    if existing and _is_summary_stale(existing):
        logger.info(
            'memory.get_or_create_summary.stale_summary',
            user_id=str(user_id),
            book_id=str(book_id),
            stored_prompt_version=(getattr(existing, 'metadata_', None) or {}).get('prompt_version'),
            current_prompt_version=CONVERSATION_SUMMARY_SYSTEM.version,
        )

    summary = await _generate_summary(db, user_id, book_id, existing)
    elapsed = int((time.monotonic() - t0) * 1000)
    _log_summary_result(
        'memory.get_or_create_summary.generated',
        total, len(summary) if summary else 0, elapsed, user_id, book_id,
    )
    return summary


async def _load_older_messages(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
) -> list[ChatMessage]:
    """Load all messages for a conversation, capped at 200."""
    async with db_error_guard('_load_older_messages', user_id=str(user_id), book_id=str(book_id)):
        result = await db.execute(
            select(ChatMessage)
            .where(
                ChatMessage.user_id == user_id,
                ChatMessage.book_id == book_id,
                ChatMessage.deleted_at.is_(None),
            )
            .order_by(ChatMessage.created_at)
            .limit(CONVERSATION_MEMORY_LIMIT)
        )
        return list(result.scalars().all())


def _build_summary_prompt(
    older: list[ChatMessage],
    existing_summary: str,
) -> list:
    """Build the system + human message pair for the LLM summary call."""
    conversation_text = _format_conversation(older)
    system_content = CONVERSATION_SUMMARY_SYSTEM.template

    if existing_summary:
        preamble = (
            f'Existing summary:\n{existing_summary}\n\n'
            'Update this summary to incorporate the new conversation below:'
        )
    else:
        preamble = 'New conversation to summarize:'

    human_content = CONVERSATION_SUMMARY_HUMAN.render(
        preamble=preamble,
        conversation_text=conversation_text,
    )

    return [
        SystemMessage(content=system_content),
        HumanMessage(content=human_content),
    ]


async def _save_summary(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
    existing: 'ConversationSummary | None',
    summary_text: str,
    message_count: int,
    model_name: str | None = None,
) -> None:
    """Persist the generated summary to the database."""
    from app.models.conversation_summary import ConversationSummary
    metadata = _build_summary_metadata(model_name)
    async with db_error_guard('_save_summary', user_id=str(user_id), book_id=str(book_id)):
        if existing:
            existing.summary = summary_text
            existing.message_count = message_count
            existing.metadata_ = metadata
            await db.flush()
        else:
            new_summary = ConversationSummary(
                user_id=user_id,
                book_id=book_id,
                summary=summary_text,
                message_count=message_count,
                metadata_=metadata,
            )
            db.add(new_summary)
            await db.flush()


async def _generate_summary(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
    existing: 'ConversationSummary | None' = None,
) -> str:
    """Generate a compressed summary of older conversation turns."""
    all_messages = await _load_older_messages(db, user_id, book_id)

    if len(all_messages) <= MAX_RECENT:
        return existing.summary if existing else ''

    older = all_messages[:-MAX_RECENT]
    existing_summary = existing.summary if existing else ''

    messages = _build_summary_prompt(older, existing_summary)

    summary_data = await safe_llm_invoke(
        messages,
        fallback=None,
        log_label='Conversation summary',
        schema_class=ConversationSummaryData,
        user_id=str(user_id),
        book_id=str(book_id),
        template=CONVERSATION_SUMMARY_SYSTEM,
    )

    # Best-effort model attribution: safe_llm_invoke doesn't surface the
    # resolved model in its return value. We tag with the configured
    # default — close enough for provenance, since prompt_version (not
    # model) is the primary staleness signal we act on.
    try:
        from app.config import get_settings
        model_name = get_settings().default_model
    except Exception:  # noqa: BLE001 — provenance only, never fatal
        model_name = None

    if summary_data and isinstance(summary_data, dict):
        summary_text = _summarize_to_text(summary_data)
    else:
        summary_text = existing_summary

    await _save_summary(
        db, user_id, book_id, existing, summary_text, len(all_messages), model_name,
    )
    return summary_text


def _format_conversation(messages: list[ChatMessage]) -> str:
    """Format chat messages into readable text for summarization.

    Applies input sanitization and token budgeting.
    """
    budget = TokenBudget(model='glm-4.7-flash', response_reserve=4000)
    parts: list[str] = []
    for msg in messages:
        role = 'User' if msg.role == 'user' else 'Companion'
        # Sanitize each message against prompt injection
        content = sanitize_chat_message(msg.content[:500])
        line = f'{role}: {content}'
        # Apply token budget
        line = budget.add(line, label=f'conversation_msg_{msg.id}')
        if not line:
            break
        parts.append(line)
    return '\n'.join(parts)


def _summarize_to_text(data: dict) -> str:
    """Convert structured ConversationSummaryData to a readable text summary."""
    topics = data.get('key_topics', [])
    insights = data.get('insights', [])
    questions = data.get('unresolved_questions', [])

    parts: list[str] = []
    if topics:
        parts.append(f'Key topics: {", ".join(topics)}.')
    if insights:
        parts.append(f'Insights: {" ".join(insights)}.')
    if questions:
        parts.append(f'Unresolved: {" ".join(questions)}.')

    return ' '.join(parts) if parts else json.dumps(data)
