"""P3.1 tests: conversation summary metadata provenance + staleness detection.

Validates that:
- ``_build_summary_metadata`` records prompt_version, schema_version, model,
  and a generated_at ISO timestamp.
- ``_is_summary_stale`` correctly classifies NULL metadata, mismatched
  prompt_version, mismatched schema_version, and non-dict metadata as stale.
- A fresh summary (current prompt_version + schema_version) is not stale.
- ``_save_summary`` populates metadata on both the insert and update paths.

These tests use plain fakes — no DB, no LLM call. The integration between
``get_or_create_summary`` → ``_is_summary_stale`` is verified at the
function level; full async-DB coverage lives in the existing conversation
memory integration suite.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

import pytest

from app.prompts import CONVERSATION_SUMMARY_SYSTEM
from app.services.conversation_memory import (
    MEMORY_SCHEMA_VERSION,
    _build_summary_metadata,
    _is_summary_stale,
)


@dataclass
class FakeSummary:
    """Minimal stand-in for the ConversationSummary ORM model.

    Only the fields ``_is_summary_stale`` reads are needed: ``metadata_``.
    Other ORM fields (summary, message_count, user_id, ...) are kept to
    keep the fake realistic if future tests exercise more code paths.
    """

    summary: str = ''
    message_count: int = 0
    metadata_: dict[str, Any] | None = None
    user_id: Any = field(default_factory=uuid4)
    book_id: Any = field(default_factory=uuid4)


# ---------------------------------------------------------------------------
# _build_summary_metadata
# ---------------------------------------------------------------------------


def test_metadata_records_current_prompt_version():
    """The metadata block must capture the live prompt_version verbatim."""
    meta = _build_summary_metadata(model_name='glm-4.7-flash')
    assert meta['prompt_version'] == CONVERSATION_SUMMARY_SYSTEM.version


def test_metadata_records_schema_version_constant():
    """schema_version must match the module-level MEMORY_SCHEMA_VERSION."""
    meta = _build_summary_metadata(model_name='glm-4.7-flash')
    assert meta['schema_version'] == MEMORY_SCHEMA_VERSION


def test_metadata_records_model_name():
    meta = _build_summary_metadata(model_name='deepseek-chat')
    assert meta['model'] == 'deepseek-chat'


def test_metadata_falls_back_to_unknown_when_model_missing():
    """When model attribution is unavailable, 'unknown' is the explicit sentinel.

    This is intentional: NULL model would collide with "pre-P3.1 row" in
    queries; 'unknown' makes "couldn't attribute" distinguishable from
    "row predates metadata tracking".
    """
    meta = _build_summary_metadata(model_name=None)
    assert meta['model'] == 'unknown'


def test_metadata_generated_at_is_iso8601_utc():
    """generated_at must parse as an ISO 8601 string with tzinfo=UTC."""
    meta = _build_summary_metadata(model_name='glm-4.7-flash')
    ts = datetime.fromisoformat(meta['generated_at'])
    assert ts.tzinfo == timezone.utc


# ---------------------------------------------------------------------------
# _is_summary_stale
# ---------------------------------------------------------------------------


def test_stale_when_summary_is_none():
    """No existing summary → stale (forces creation on first call)."""
    assert _is_summary_stale(None) is True


def test_stale_when_metadata_is_none():
    """NULL metadata = pre-P3.1 row written by older code → stale.

    This is the backfill trigger: legacy rows must not be trusted blindly.
    """
    fake = FakeSummary(metadata_=None)
    assert _is_summary_stale(fake) is True


def test_stale_when_prompt_version_mismatches():
    """A row generated by prompt v0 (or any non-current version) is stale.

    Catches the case where the system prompt template changed but the
    summary row hasn't been regenerated yet.
    """
    fake = FakeSummary(metadata_={
        'prompt_version': CONVERSATION_SUMMARY_SYSTEM.version - 1,
        'schema_version': MEMORY_SCHEMA_VERSION,
    })
    assert _is_summary_stale(fake) is True


def test_stale_when_schema_version_mismatches():
    """A row written against an older schema_version is stale.

    Catches the case where we extended the JSON shape (added fields,
    changed semantics) — old rows must regenerate to match new shape.
    """
    fake = FakeSummary(metadata_={
        'prompt_version': CONVERSATION_SUMMARY_SYSTEM.version,
        'schema_version': MEMORY_SCHEMA_VERSION + 1,
    })
    assert _is_summary_stale(fake) is True


def test_stale_when_metadata_is_not_a_dict():
    """Defensive: corrupted rows (list/str metadata) treated as stale.

    Shouldn't happen under normal writes, but the JSONB column accepts
    any JSON shape. Better to refresh than to crash.
    """
    fake_list = FakeSummary(metadata_=['not', 'a', 'dict'])  # type: ignore[arg-type]
    assert _is_summary_stale(fake_list) is True

    fake_str = FakeSummary(metadata_='oops')  # type: ignore[arg-type]
    assert _is_summary_stale(fake_str) is True


def test_not_stale_when_versions_match():
    """Fresh row: current prompt_version + current schema_version."""
    fake = FakeSummary(metadata_={
        'prompt_version': CONVERSATION_SUMMARY_SYSTEM.version,
        'schema_version': MEMORY_SCHEMA_VERSION,
        'model': 'glm-4.7-flash',
        'generated_at': '2026-06-16T00:00:00+00:00',
    })
    assert _is_summary_stale(fake) is False


def test_not_stale_ignores_extra_metadata_fields():
    """Forward-compat: extra keys in metadata (confidence, source tags)
    must NOT trip the staleness check. JSONB is intentionally open-shaped."""
    fake = FakeSummary(metadata_={
        'prompt_version': CONVERSATION_SUMMARY_SYSTEM.version,
        'schema_version': MEMORY_SCHEMA_VERSION,
        'confidence': 0.87,
        'source_tags': ['user_stated', 'model_inferred'],
        'future_field_we_might_add': '...should not break staleness...',
    })
    assert _is_summary_stale(fake) is False


# ---------------------------------------------------------------------------
# Integration: _save_summary propagates metadata on both insert and update
# ---------------------------------------------------------------------------


class _FakeAsyncSession:
    """Bare-bones AsyncSession double: records flushes + inserted objects.

    We avoid the real session because the SQLAlchemy async flush path
    needs a live DB. _save_summary calls ``db.add`` synchronously
    (SQLAlchemy's Session.add is sync) and ``db.flush`` via await.
    """

    def __init__(self) -> None:
        self.added: list[Any] = []
        self.flush_count = 0

    def add(self, obj: Any) -> None:
        self.added.append(obj)

    async def flush(self) -> None:
        self.flush_count += 1


@pytest.mark.asyncio
async def test_save_summary_insert_populates_metadata():
    """Insert path: a brand-new ConversationSummary gets metadata stamped.

    Uses the real ConversationSummary ORM model so the metadata_ attribute
    (mapped to the JSONB 'metadata' column) is exercised end-to-end.
    """
    from app.models.conversation_summary import ConversationSummary
    from app.services.conversation_memory import _save_summary

    db = _FakeAsyncSession()
    user_id = uuid4()
    book_id = uuid4()

    await _save_summary(
        db=db,
        user_id=user_id,
        book_id=book_id,
        existing=None,
        summary_text='Key topics: ring, fellowship.',
        message_count=42,
        model_name='glm-4.7-flash',
    )

    assert len(db.added) == 1
    inserted: ConversationSummary = db.added[0]
    assert inserted.summary == 'Key topics: ring, fellowship.'
    assert inserted.message_count == 42
    assert inserted.metadata_ is not None
    assert inserted.metadata_['prompt_version'] == CONVERSATION_SUMMARY_SYSTEM.version
    assert inserted.metadata_['schema_version'] == MEMORY_SCHEMA_VERSION
    assert inserted.metadata_['model'] == 'glm-4.7-flash'
    assert 'generated_at' in inserted.metadata_


@pytest.mark.asyncio
async def test_save_summary_update_overwrites_metadata():
    """Update path: existing row's metadata is replaced, not merged.

    Important: if we did a shallow merge, a stale prompt_version left over
    from an older write could survive a fresh regeneration and confuse
    the next staleness check. We assign a fresh dict each time.
    """
    from app.services.conversation_memory import _save_summary

    db = _FakeAsyncSession()
    user_id = uuid4()
    book_id = uuid4()

    # An "old" row with stale metadata — wrong prompt_version.
    existing = FakeSummary(
        summary='stale text',
        message_count=10,
        metadata_={'prompt_version': 0, 'schema_version': 0, 'model': 'old'},
    )

    await _save_summary(
        db=db,
        user_id=user_id,
        book_id=book_id,
        existing=existing,  # type: ignore[arg-type]
        summary_text='refreshed text',
        message_count=42,
        model_name='glm-4.7-flash',
    )

    # No insert path taken; existing was mutated in-place.
    assert db.added == []
    assert existing.summary == 'refreshed text'
    assert existing.message_count == 42
    assert existing.metadata_['prompt_version'] == CONVERSATION_SUMMARY_SYSTEM.version
    assert existing.metadata_['schema_version'] == MEMORY_SCHEMA_VERSION
    # Old prompt_version=0 must NOT linger — fresh dict, not merge.
    assert existing.metadata_['model'] == 'glm-4.7-flash'
