"""B3 — quality-disclosure SSE metadata event on provider fallback.

When primary fails mid-stream and a different (often cheaper / weaker)
model takes over, the user sees the response style change mid-message
without explanation. Common user reaction: "the AI broke / the book is
bad / my prompt was wrong" — when the real cause is a silent provider
downgrade.

The metadata event gives clients a hook to surface "AI response
generated by fallback model — quality may be reduced" so users attribute
the change correctly.

These tests pin:
- Event schema (type/request_id/model/fallback_used/primary_model)
- JSON-validity (clients must be able to parse it)
- Emission BEFORE fallback content chunks (so client UI knows upfront)
- No emission when no fallback is available
"""

from __future__ import annotations

import json

import pytest

from app.services.companion.stream_cache import sse_metadata_event


def test_sse_metadata_event_basic_schema():
    """Event carries the 4 mandatory fields in the documented shape."""
    chunk = sse_metadata_event(
        request_id='req-abc',
        model='deepseek-chat',
        fallback_used=True,
        primary_model='glm-4.7-flash',
        primary_provider='glm',
    )
    assert chunk.startswith('data: ')
    assert chunk.endswith('\n\n')
    payload = json.loads(chunk[len('data: '):-2])
    assert payload['type'] == 'metadata'
    assert payload['request_id'] == 'req-abc'
    assert payload['model'] == 'deepseek-chat'
    assert payload['fallback_used'] is True
    assert payload['primary_model'] == 'glm-4.7-flash'
    assert payload['primary_provider'] == 'glm'


def test_sse_metadata_event_omits_optional_fields_when_none():
    """primary_model / primary_provider are optional — clients should be
    able to handle their absence (e.g. if a future caller doesn't know
    the failed model)."""
    chunk = sse_metadata_event(
        request_id='req-xyz',
        model='glm-4.7-flash',
        fallback_used=False,
    )
    payload = json.loads(chunk[len('data: '):-2])
    assert 'primary_model' not in payload
    assert 'primary_provider' not in payload
    assert payload['fallback_used'] is False


def test_sse_metadata_event_special_chars_in_model_name():
    """Model names can contain dots, dashes, slashes — JSON encoder must
    handle them without breaking the SSE frame."""
    chunk = sse_metadata_event(
        request_id='req-special',
        model='gpt-4.1-nano-2025-04-14',
        fallback_used=True,
        primary_model='glm-4.7-flash',
    )
    # The frame is exactly one 'data:' line + \n\n. No embedded \n leaks.
    assert chunk.count('\n') == 2
    payload = json.loads(chunk[len('data: '):-2])
    assert payload['model'] == 'gpt-4.1-nano-2025-04-14'


def test_sse_metadata_event_is_json_parseable_by_client_parser():
    """A standard SSE parser splits on '\\n\\n' and JSON-parses the data
    payload. The chunk must round-trip cleanly through that pipeline."""
    chunk = sse_metadata_event(
        request_id='req-parse',
        model='m',
        fallback_used=True,
        primary_model='p',
    )
    # Strip the 'data: ' prefix and trailing \n\n, parse the body.
    body = chunk[6:-2]
    parsed = json.loads(body)
    assert parsed['type'] == 'metadata'


# ---------------------------------------------------------------------------
# Streaming integration: metadata event fires before fallback chunks
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_metadata_event_emitted_before_fallback_chunks_on_primary_failure():
    """When primary raises mid-stream, the metadata event must come BEFORE
    any fallback content chunk — so the client UI can show the downgrade
    notice upfront instead of after tokens start arriving.
    """
    import asyncio
    from unittest.mock import MagicMock, patch, AsyncMock
    from app.services.companion import streaming

    # Fake primary LLM that raises immediately (no chunks emitted).
    class FailingLLM:
        async def astream(self, messages):
            raise RuntimeError('primary dead')
            yield  # noqa: unreachable — generator function for type compat

    # Fake fallback that emits one content chunk.
    class FakeFallbackLLM:
        async def astream(self, messages):
            class C:
                content = 'fallback content'
            yield C()

    # Fake provider state with healthy circuit (so primary is attempted).
    primary_state = MagicMock()
    primary_state.config.name = 'glm'
    primary_state.config.default_model = 'glm-4.7-flash'
    primary_state.circuit.allow_request = AsyncMock(return_value=True)

    fallback_state = MagicMock()
    fallback_state.config.name = 'deepseek'
    fallback_state.config.default_model = 'deepseek-chat'
    fallback_state.circuit.allow_request = AsyncMock(return_value=True)
    fallback_state.circuit.record_success = AsyncMock()

    chunks_emitted: list[str] = []

    with patch.object(streaming, 'get_llm', side_effect=[FailingLLM(), FakeFallbackLLM()]), \
         patch.object(streaming, '_handle_stream_failure', new=AsyncMock()), \
         patch('app.services.companion.stream_fallback.get_llm', return_value=FakeFallbackLLM()), \
         patch('app.services.companion.stream_fallback.resolve_fallback_provider', return_value=fallback_state), \
         patch('app.services.companion.stream_fallback.quick_safety_check', return_value=True), \
         patch('app.services.llm.registry.get_registry') as mock_reg:
        mock_reg.return_value.record_latency = MagicMock()

        async for chunk in streaming._stream_from_provider(
            state=primary_state,
            provider_name='glm',
            model_used='glm-4.7-flash',
            messages=[],
            collected_parts=[],
            request_id='req-meta-1',
            start_time=0.0,
            user_id='00000000-0000-0000-0000-000000000001',
            book_id='00000000-0000-0000-0000-000000000002',
            lang='en',
            cancelled=asyncio.Event(),
        ):
            chunks_emitted.append(chunk)

    # First non-DONE chunk must be the metadata event.
    meta_chunks = [
        c for c in chunks_emitted
        if c.startswith('data: ') and '"type": "metadata"' in c
    ]
    assert meta_chunks, 'metadata event was not emitted on primary failure'
    meta_payload = json.loads(meta_chunks[0][len('data: '):-2])
    assert meta_payload['fallback_used'] is True
    assert meta_payload['primary_model'] == 'glm-4.7-flash'
    assert meta_payload['primary_provider'] == 'glm'
    assert meta_payload['model'] == 'deepseek-chat'

    # The metadata chunk must come before any content chunk.
    meta_idx = chunks_emitted.index(meta_chunks[0])
    content_indices = [
        i for i, c in enumerate(chunks_emitted)
        if c.startswith('data: ') and '"content"' in c
    ]
    assert all(meta_idx < i for i in content_indices), (
        'metadata event must precede content chunks'
    )


@pytest.mark.asyncio
async def test_no_metadata_event_when_no_fallback_available():
    """If no fallback provider exists, stream_fallback will emit a single
    fallback-error chunk. We must NOT emit a metadata event claiming a
    fallback is happening — that would lie to the client.
    """
    import asyncio
    from unittest.mock import MagicMock, patch, AsyncMock
    from app.services.companion import streaming

    class FailingLLM:
        async def astream(self, messages):
            raise RuntimeError('primary dead')
            yield  # noqa: unreachable

    primary_state = MagicMock()
    primary_state.config.name = 'glm'
    primary_state.config.default_model = 'glm-4.7-flash'
    primary_state.circuit.allow_request = AsyncMock(return_value=True)

    chunks_emitted: list[str] = []

    with patch.object(streaming, 'get_llm', return_value=FailingLLM()), \
         patch.object(streaming, '_handle_stream_failure', new=AsyncMock()), \
         patch('app.services.companion.stream_fallback.resolve_fallback_provider', return_value=None), \
         patch('app.services.llm.registry.get_registry') as mock_reg:
        mock_reg.return_value.record_latency = MagicMock()

        async for chunk in streaming._stream_from_provider(
            state=primary_state,
            provider_name='glm',
            model_used='glm-4.7-flash',
            messages=[],
            collected_parts=[],
            request_id='req-no-fb',
            start_time=0.0,
            user_id='00000000-0000-0000-0000-000000000001',
            book_id='00000000-0000-0000-0000-000000000002',
            lang='en',
            cancelled=asyncio.Event(),
        ):
            chunks_emitted.append(chunk)

    # No metadata event in this case.
    meta_chunks = [c for c in chunks_emitted if '"type": "metadata"' in c]
    assert not meta_chunks, (
        'metadata event emitted when no fallback available — would mislead client'
    )
