"""Cache helpers for companion streaming — lookup, store, and emit cached responses."""

import json
from collections.abc import AsyncGenerator
from uuid import UUID

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from app.services.companion.context import _save_message
from app.utils.output_filter import filter_output

logger = structlog.get_logger('read-pal.companion')


# P4.4: shared by try_stream_cache and persist_stream_result so the cache
# key can't drift between the write path and the lookup path. The literal
# 'companion_stream' namespace + the str(user_id) normalization used to be
# duplicated — adding a new key component (e.g. persona version) in one
# path without the other would silently make writes miss lookups.
_CACHE_NAMESPACE = 'companion_stream'
# P4.4: shared by try_stream_cache and persist_stream_result. Both paths
# tolerate cache infrastructure failures (Redis down, serializer glitch)
# by degrading gracefully — we'd rather serve a fresh LLM call than 500
# the request because the cache layer is flaky.
_CACHE_OP_ERRORS = (ValueError, ConnectionError, RuntimeError)


def _stream_cache_key(messages: list, user_id: str | UUID | None, lang: str | None) -> str:
    """Build the per-user / per-lang companion stream cache key.

    ``user_id`` is normalized via ``str()`` so callers can pass either a UUID
    or its string form — the cache key matches either way.
    """
    from app.services.llm import _cache_key
    return _cache_key(
        messages, _CACHE_NAMESPACE,
        user_id=str(user_id) if user_id is not None else None,
        lang=lang,
    )


async def try_stream_cache(
    messages: list, user_id: str | None = None, lang: str | None = None,
) -> str | None:
    """Check LLM cache for a matching stream response. Returns cached text or None.

    ``user_id`` is required to scope the cache key per-user — without it two users
    with identical prompts would share a cached streamed reply (privacy leak).
    ``lang`` prevents cross-language leaks — the system prompt is built per-lang
    outside the cache, so without it a user who flips language gets the prior
    language's cached response.
    """
    try:
        from app.services.llm import _cache_get
        return await _cache_get(_stream_cache_key(messages, user_id, lang))
    except _CACHE_OP_ERRORS as exc:
        logger.warning('companion.streaming.cache_check_failed', error=str(exc)[:200])
        return None


def sse_chunk(
    content: str,
    *,
    request_id: str | None = None,
    seq: int | None = None,
) -> str:
    """Format a content string as an SSE data chunk.

    D1: when ``request_id`` and ``seq`` are both provided, emit an
    ``id: {request_id}:{seq}\\n`` line BEFORE the ``data:`` line. The id
    becomes the value of the ``Last-Event-ID`` HTTP header on client
    reconnect, letting the server replay buffered chunks from the right
    offset (D2 + D3). When either is None (terminal/error frames, cached
    responses), no id line — those frames don't need replay semantics.
    """
    data_line = f'data: {json.dumps({"content": content})}\n\n'
    if request_id is not None and seq is not None:
        return f'id: {request_id}:{seq}\n{data_line}'
    return data_line


def sse_metadata_event(
    *,
    request_id: str,
    model: str,
    fallback_used: bool,
    primary_model: str | None = None,
    primary_provider: str | None = None,
    seq: int | None = None,
) -> str:
    """Format a metadata SSE chunk — signals which model produced the response.

    B3: emitted once BEFORE the first fallback chunk when primary fails and a
    cheaper/weaker model takes over. Lets the client surface "AI response
    generated by fallback model — quality may be reduced" so users don't
    misattribute the style change to a bug in their book / prompt.

    D1: ``seq`` (optional) emits an ``id:`` line so the metadata event is
    replayable too — the client must see the downgrade notice on reconnect
    even if the original emit happened before any content chunk.

    Schema pinned for client compatibility:
      type: 'metadata'         — discriminator vs 'content' chunks
      request_id: str          — matches the first SSE frame's request_id
      model: str               — the model that actually produced the output
      fallback_used: bool      — always True for this event (we only emit on fallback)
      primary_model: str|None  — the model that FAILED (for "downgraded from X" UI)
      primary_provider: str|None — the provider that failed
    """
    payload: dict = {
        'type': 'metadata',
        'request_id': request_id,
        'model': model,
        'fallback_used': fallback_used,
    }
    if primary_model is not None:
        payload['primary_model'] = primary_model
    if primary_provider is not None:
        payload['primary_provider'] = primary_provider
    data_line = f'data: {json.dumps(payload)}\n\n'
    if seq is not None:
        return f'id: {request_id}:{seq}\n{data_line}'
    return data_line


async def emit_cached_response(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
    message: str,
    cached_response: str,
) -> AsyncGenerator[str, None]:
    """Yield cached response as SSE and persist ONLY the user's message.

    The assistant side already exists in chat history from the original call
    that populated the cache — writing it again would duplicate the row on
    every cache hit (popular prompts → storage bloat).

    Yields nothing (empty generator) if cache content fails safety filter.
    """
    safe = filter_output(cached_response, context='companion_stream')
    if not safe:
        return
    yield sse_chunk(safe)
    yield 'data: [DONE]\n\n'
    await _save_message(db, user_id, book_id, 'user', message)


async def try_emit_cached(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
    message: str,
    messages: list[dict],
    lang: str | None = None,
) -> AsyncGenerator[str, None]:
    """Try cache lookup and emit cached response. Yields nothing on miss."""
    cached_response = await try_stream_cache(messages, str(user_id), lang=lang)
    if not cached_response:
        return
    async for chunk in emit_cached_response(
        db, user_id, book_id, message, cached_response,
    ):
        yield chunk


async def persist_stream_result(
    db: AsyncSession,
    user_id: UUID,
    book_id: UUID,
    message: str,
    messages: list,
    collected_parts: list[str],
    request_id: str,
    lang: str | None = None,
) -> UUID | None:
    """Filter, cache, persist the streaming result; return the assistant
    message's DB id (None when nothing was persisted) so the caller can
    hand the real id back to the client — feedback ratings FK against it."""
    assistant_content = ''.join(collected_parts)
    if assistant_content:
        assistant_content = filter_output(assistant_content, context='companion_stream')

    if assistant_content:
        try:
            from app.services.llm import _cache_set
            await _cache_set(
                _stream_cache_key(messages, user_id, lang),
                assistant_content,
            )
        except _CACHE_OP_ERRORS as exc:
            logger.warning('companion.streaming.cache_write_failed', error=str(exc)[:200])

    # Always persist the user's message — it's valid input even when the AI
    # produced nothing (rate-limited, circuit open, provider unavailable).
    # The companion UI promises "your messages will be saved"; losing the
    # user's side of the conversation on AI failure breaks that promise and
    # orphans the chat history.
    await _save_message(db, user_id, book_id, 'user', message)

    if not assistant_content:
        logger.warning(
            'companion.stream.empty_response',
            request_id=request_id,
            book_id=str(book_id),
        )
        return None

    return await _save_message(db, user_id, book_id, 'assistant', assistant_content)
