/**
 * Discussion Guide Export
 *
 * Generates a polished HTML discussion guide from annotations and book metadata.
 * Output can be copied, downloaded as HTML, or printed to PDF via window.print().
 */

import type { Annotation } from '@read-pal/shared';
import { DISCUSSION_GUIDE_STYLES } from '@/lib/discussion-guide-styles';
import {
  escapeHtml,
  renderStats,
  renderThemes,
  renderQuotes,
  renderNotes,
  renderDiscussionQuestions,
  type BookMeta,
  type ReadingStats,
} from '@/lib/discussion-guide-sections';

export type { BookMeta, ReadingStats };

export interface DiscussionGuideOptions {
  book: BookMeta;
  annotations: Annotation[];
  stats?: ReadingStats;
  discussionQuestions?: string[];
}

/**
 * Generate a discussion guide as a full HTML document string.
 */
export function generateDiscussionGuideHtml(
  options: DiscussionGuideOptions,
): string {
  const { book, annotations, stats, discussionQuestions } = options;

  const safeStats: ReadingStats = {
    totalPages: stats?.totalPages ?? book.totalPages,
    currentPage: stats?.currentPage ?? book.currentPage,
    progress: stats?.progress ?? book.progress,
    totalAnnotations: stats?.totalAnnotations ?? annotations.length,
    highlights: stats?.highlights ?? annotations.filter((a) => a.type === 'highlight').length,
    notes: stats?.notes ?? annotations.filter((a) => a.type === 'note').length,
    bookmarks: stats?.bookmarks ?? annotations.filter((a) => a.type === 'bookmark').length,
  };

  const pct = safeStats.progress != null ? Math.round(safeStats.progress) : 0;

  const sections = [
    renderStats(book, safeStats),
    renderThemes(annotations),
    renderQuotes(annotations),
    renderNotes(annotations),
    renderDiscussionQuestions(discussionQuestions ?? []),
  ]
    .filter(Boolean)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Discussion Guide: ${escapeHtml(book.title)}</title>
  ${DISCUSSION_GUIDE_STYLES}
</head>
<body>
  <header>
    <h1>${escapeHtml(book.title)}</h1>
    <div class="author">by ${escapeHtml(book.author)}</div>
    <div class="meta">Discussion Guide &middot; ${new Date().toLocaleDateString()} &middot; ${pct}% complete</div>
  </header>
  ${sections}
  <div class="footer">Generated by read-pal</div>
</body>
</html>`;
}

/**
 * Copy the discussion guide HTML to clipboard as rich text.
 * Falls back to copying the raw HTML.
 */
export async function copyDiscussionGuide(html: string): Promise<boolean> {
  if (navigator.clipboard?.write) {
    try {
      const blob = new Blob([html], { type: 'text/html' });
      const textBlob = new Blob(
        [html.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()],
        { type: 'text/plain' },
      );
      await navigator.clipboard.write([
        new ClipboardItem({
          'text/html': blob,
          'text/plain': textBlob,
        }),
      ]);
      return true;
    } catch (err) {
      console.warn('Clipboard write failed, falling back to writeText', err);
    }
  }
  if (navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(html);
      return true;
    } catch (err) {
      console.warn('Clipboard writeText also failed', err);
    }
  }
  return false;
}

/**
 * Download the discussion guide as an HTML file.
 */
export function downloadDiscussionGuide(
  html: string,
  bookTitle: string,
): void {
  const safeTitle = bookTitle.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-').slice(0, 40);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `discussion-guide-${safeTitle}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Open the discussion guide in a new window for printing.
 */
export function printDiscussionGuide(html: string): void {
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.onload = () => {
    win.print();
  };
}
