/**
 * SSE Stream Consumer
 *
 * Shared utility for consuming Server-Sent Events streams.
 * Extracted from CompanionChat, chat/page, and friend/page.
 */

/**
 * Consume an SSE stream from the backend.
 *
 * - `onToken` is called for each content chunk.
 * - `onMeta` is called for non-content metadata frames (e.g. ``request_id``,
 *   B3 quality-disclosure ``metadata`` events). Multiple meta frames may
 *   arrive in a single stream — the callback fires once per frame.
 * - `onId` is called when an ``id:`` line is seen (D1). The id is the raw
 *   value (e.g. ``req_abc:3``) — callers store it as Last-Event-ID for
 *   reconnect (D4).
 * - `onDone` is called when the stream completes ([DONE] or clean close).
 * - `onError` is called on stream errors, with the error string. The string
 *   ``'persist_failed'`` is special: it means the streamed content was
 *   produced but DB persistence failed — callers should NOT retry the stream
 *   in that case (the user already saw the response).
 *
 * Returns an AbortController so the caller can cancel.
 */
import { warn } from './logger';

/**
 * Metadata frame shape. ``request_id`` is always present on the first
 * frame (so the client can cancel later). The remaining fields are
 * populated by the B3 quality-disclosure ``metadata`` event when a
 * fallback provider took over mid-stream — callers surface this as a
 * "response generated by fallback model — quality may be reduced" notice.
 */
export type SSEToolResult = { tool?: string; ok?: boolean; latency_ms?: number };

export type SSEProposal = {
  id?: string;
  tool?: string;
  args?: Record<string, unknown>;
  preview?: string;
};

export type SSEMeta = {
  request_id?: string;
  type?: 'metadata' | 'message_id' | 'tool_status' | 'tool_proposals';
  results?: SSEToolResult[];
  proposals?: SSEProposal[];
  message_id?: string;
  model?: string;
  fallback_used?: boolean;
  primary_model?: string;
  primary_provider?: string;
  // Research stream frames (J2): phase progress + final brief payload.
  // Chat streams never carry these keys, so forwarding is additive.
  phase?: 'searching' | 'sources' | 'synthesizing';
  sources?: SSEResearchSource[];
  books_searched?: number;
  brief?: Record<string, unknown>;
  cancelled?: boolean;
};

export type SSEResearchSource = {
  source_id: number;
  book_id?: string | null;
  book_title: string;
  author?: string;
  chapter_title?: string;
};
export type SSEError = 'persist_failed' | 'internal_error' | (string & {});

export function consumeSSEStream(
  response: Response,
  onToken: (token: string) => void,
  onDone: () => void,
  onError: (err: SSEError) => void,
  parentSignal?: AbortSignal,
  onMeta?: (meta: SSEMeta) => void,
  onId?: (id: string) => void,
): AbortController {
  const controller = new AbortController();
  const reader = response.body?.getReader();

  // Link parent signal so aborting the fetch also aborts the stream reader
  if (parentSignal) {
    if (parentSignal.aborted) {
      controller.abort();
    } else {
      parentSignal.addEventListener('abort', () => controller.abort(), { once: true });
    }
  }

  let finalized = false;
  const safeDone = () => { if (!finalized) { finalized = true; onDone(); } };
  const safeError = (err: SSEError) => { if (!finalized) { finalized = true; onError(err); } };

  if (!reader) {
    safeError('No response body');
    return controller;
  }

  const decoder = new TextDecoder();
  let buffer = '';

  const processChunk = (chunk: string): void => {
    buffer += chunk;
    const lines = buffer.split(/\r?\n/);
    // Keep the last (potentially incomplete) line in the buffer
    buffer = lines.pop() || '';

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      // D1: ``id: <value>`` line precedes the data line. Capture it for
      // D4 reconnect — the value is sent back as Last-Event-ID so the
      // server can replay buffered chunks from the right offset.
      if (onId && trimmed.startsWith('id: ')) {
        onId(trimmed.slice(4));
        continue;
      }

      if (!trimmed.startsWith('data: ')) continue;

      const payload = trimmed.slice(6); // strip "data: "
      if (payload === '[DONE]') {
        safeDone();
        controller.abort();
        return;
      }

        try {
          const parsed = JSON.parse(payload) as {
            token?: string;
            content?: string;
            error?: string;
            request_id?: string;
            id?: string;
            results?: SSEToolResult[];
            proposals?: SSEProposal[];
            type?: string;
            model?: string;
            fallback_used?: boolean;
            primary_model?: string;
            primary_provider?: string;
            phase?: 'searching' | 'sources' | 'synthesizing';
            sources?: SSEResearchSource[];
            books_searched?: number;
            brief?: Record<string, unknown>;
            cancelled?: boolean;
          };
        // B3: quality-disclosure metadata event. Emitted BEFORE fallback
        // chunks when primary provider failed mid-stream — surfaces the
        // model downgrade so the client can warn the user that response
        // style change is intentional, not a bug.
        // Server hands back the assistant message's real DB id after
        // persist — feedback ratings FK against chat_messages.id.
        if (parsed.type === 'message_id' && onMeta) {
          onMeta({ type: 'message_id', message_id: parsed.id });
        }
        // Tool-phase footprint (ephemeral hint; no replay id by design).
        if (parsed.type === 'tool_status' && onMeta) {
          onMeta({ type: 'tool_status', results: parsed.results || [] });
        }
        // v2 action proposals: user-confirmed writes (ephemeral by design).
        if (parsed.type === 'tool_proposals' && onMeta) {
          onMeta({ type: 'tool_proposals', proposals: parsed.proposals || [] });
        }
        if (parsed.type === 'metadata' && onMeta) {
          onMeta({
            type: 'metadata',
            request_id: parsed.request_id,
            model: parsed.model,
            fallback_used: parsed.fallback_used,
            primary_model: parsed.primary_model,
            primary_provider: parsed.primary_provider,
          });
        }
        // First-frame request_id so the client can cancel the stream by id.
        if (onMeta && (parsed.request_id !== undefined) && parsed.type !== 'metadata') {
          onMeta({ request_id: parsed.request_id });
        }
        // Research stream frames (J2): forward phase progress, early
        // citations, the final brief, and cooperative cancellation.
        if (onMeta && (parsed.phase !== undefined || parsed.brief !== undefined || parsed.cancelled !== undefined)) {
          onMeta({
            phase: parsed.phase,
            sources: parsed.sources,
            books_searched: parsed.books_searched,
            brief: parsed.brief,
            cancelled: parsed.cancelled,
          });
        }
        if (parsed.error) {
          safeError(parsed.error as SSEError);
          controller.abort();
          return;
        }
        const token = parsed.content || parsed.token;
        if (token) {
          onToken(token);
        }
      } catch (err) {
        warn('SSE: malformed JSON line:', payload, err);
      }
    }
  };

  (async () => {
    try {
      while (!controller.signal.aborted) {
        const result = await reader.read();
        if (result.done) break;
        processChunk(decoder.decode(result.value, { stream: true }));
      }
      // If stream ended without [DONE], still finalize
      safeDone();
    } catch (err) {
      if (!controller.signal.aborted) {
        warn('SSE: stream read failed', err);
        safeError('Stream read failed');
      }
    } finally {
      reader.releaseLock();
    }
  })();

  return controller;
}
