/**
 * Personal Book Renderer
 *
 * Assembles enriched Personal Reading Book data into a styled HTML document.
 * The design is book-like: serif fonts, warm amber/cream palette matching
 * read-pal's aesthetic, print-ready CSS.
 */

import { generateId } from '@read-pal/shared';
import type {
  EnrichedPersonalBook,
  EnrichedCover,
  EnrichedJourney,
  EnrichedHighlights,
  EnrichedNotes,
  EnrichedConversations,
  EnrichedSynthesis,
  ThemeCluster,
  HighlightContent,
  CuratedConversation,
  ReadingMilestone,
} from './PersonalBookEnricher';
import type { PersonalBookSection } from '../models/MemoryBook';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function renderPersonalBook(
  bookTitle: string,
  bookAuthor: string,
  coverUrl: string | null,
  readerName: string,
  enriched: EnrichedPersonalBook,
): { html: string; sections: PersonalBookSection[] } {
  const sections: PersonalBookSection[] = [];

  sections.push(renderCover(bookTitle, bookAuthor, coverUrl, readerName, enriched.cover));
  sections.push(renderJourney(enriched.journey));
  sections.push(renderHighlights(enriched.highlights));
  sections.push(renderNotes(bookTitle, enriched.notes));
  sections.push(renderConversations(enriched.conversations));
  sections.push(renderSynthesis(enriched.synthesis));
  sections.push(renderForward(enriched.synthesis));

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(bookTitle)} — Personal Reading Book</title>
<style>${STYLES}</style>
</head>
<body>
<div class="book">
${sections.map((s) => s.content).join('\n')}
<footer class="book-footer">
  Generated by read-pal &mdash; Your AI Reading Companion
</footer>
</div>
</body>
</html>`;

  return { html, sections };
}

// ---------------------------------------------------------------------------
// Section renderers
// ---------------------------------------------------------------------------

function renderCover(
  bookTitle: string,
  bookAuthor: string,
  coverUrl: string | null,
  readerName: string,
  cover: EnrichedCover,
): PersonalBookSection {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
  return {
    id: generateId(),
    title: '',
    type: 'cover',
    content: `
<section class="cover">
  <div class="cover-inner">
    ${coverUrl ? `<img src="${esc(coverUrl)}" alt="Cover" class="cover-image" />` : ''}
    <h1 class="cover-title">${esc(bookTitle)}</h1>
    <p class="cover-author">by ${esc(bookAuthor)}</p>
    <div class="cover-ornament">&#10023; &#10023; &#10023;</div>
    <p class="cover-subtitle">${esc(cover.subtitle)}</p>
    <p class="cover-reader">Read by ${esc(readerName)}</p>
    <p class="cover-meta">${esc(cover.readingTimeFormatted)} &mdash; ${now}</p>
    <div class="cover-badge">Personal Reading Book</div>
  </div>
</section>`,
    data: { bookTitle, bookAuthor, readerName },
  };
}

function renderJourney(journey: EnrichedJourney): PersonalBookSection {
  const milestonesHtml = journey.milestones.map((m) => `
    <div class="milestone">
      <div class="milestone-dot"></div>
      <div class="milestone-content">
        <p class="milestone-label">${esc(m.label)}</p>
        <p class="milestone-date">${formatDate(m.date)}</p>
        ${m.detail ? `<p class="milestone-detail">${esc(m.detail)}</p>` : ''}
      </div>
    </div>`).join('');

  return {
    id: generateId(),
    title: 'Your Reading Journey',
    type: 'journey',
    content: `
<section class="chapter">
  <h2 class="chapter-title">Chapter 1: Your Reading Journey</h2>
  ${journey.paceComment ? `<p class="chapter-intro">${esc(journey.paceComment)}</p>` : ''}
  <div class="timeline">
    ${milestonesHtml || '<p class="empty">No reading sessions recorded.</p>'}
  </div>
</section>`,
    data: { milestones: journey.milestones },
  };
}

function renderHighlights(highlights: EnrichedHighlights): PersonalBookSection {
  const themesHtml = highlights.themes.map((theme) => {
    const highlightsHtml = (theme.highlights && theme.highlights.length > 0)
      ? theme.highlights.map((h) => `
        <blockquote class="highlight-ref">
          <p>${esc(h.content)}</p>
          ${h.note ? `<span class="highlight-note">Note: ${esc(h.note)}</span>` : ''}
        </blockquote>`).join('')
      : (theme.highlightIds || []).map((id) =>
          `<blockquote class="highlight-ref" data-id="${esc(id)}">Highlight</blockquote>`
        ).join('');

    return `
    <div class="theme-cluster">
      <h3 class="theme-name">${esc(theme.name)}</h3>
      <p class="theme-desc">${esc(theme.description)}</p>
      <div class="theme-highlights">
        ${highlightsHtml || '<p class="empty">No highlights in this theme.</p>'}
      </div>
    </div>`;
  }).join('');

  return {
    id: generateId(),
    title: 'What Caught Your Eye',
    type: 'highlights',
    content: `
<section class="chapter">
  <h2 class="chapter-title">Chapter 2: What Caught Your Eye</h2>
  <p class="chapter-intro">The passages that made you pause, think, and highlight.</p>
  ${themesHtml || '<p class="empty">No highlights recorded.</p>'}
</section>`,
    data: { themes: highlights.themes },
  };
}

function renderNotes(bookTitle: string, notes: EnrichedNotes): PersonalBookSection {
  const tagCloudHtml = Object.entries(notes.tagCloud)
    .sort(([, a], [, b]) => b - a)
    .map(([tag, count]) => `<span class="tag" data-count="${count}">#${esc(tag)}</span>`)
    .join(' ');

  const notesHtml = notes.notes.map((n) => `
    <div class="note-entry">
      <span class="note-chapter">Chapter ${n.chapterIndex + 1}</span>
      ${n.content ? `<blockquote class="note-quote">${esc(n.content)}</blockquote>` : ''}
      <p class="note-text">${esc(n.note)}</p>
      ${n.tags.length > 0 ? `<div class="note-tags">${n.tags.map((t) => `<span class="tag">#${esc(t)}</span>`).join(' ')}</div>` : ''}
    </div>`).join('');

  return {
    id: generateId(),
    title: 'Your Voice',
    type: 'notes',
    content: `
<section class="chapter">
  <h2 class="chapter-title">Chapter 3: Your Voice</h2>
  ${notes.emotionalTrajectory ? `<p class="chapter-intro">${esc(notes.emotionalTrajectory)}</p>` : ''}
  ${Object.keys(notes.tagCloud).length > 0 ? `<div class="tag-cloud">${tagCloudHtml}</div>` : ''}
  ${notesHtml || '<p class="empty">No notes recorded.</p>'}
</section>`,
    data: { notes: notes.notes, tagCloud: notes.tagCloud },
  };
}

function renderConversations(conversations: EnrichedConversations): PersonalBookSection {
  const convosHtml = conversations.conversations.map((c) => `
    <div class="conversation">
      <div class="msg user-msg">
        <span class="msg-role">You</span>
        <p>${esc(c.userMessage)}</p>
      </div>
      <div class="msg ai-msg">
        <span class="msg-role">AI Companion</span>
        <p>${esc(c.assistantMessage)}</p>
      </div>
    </div>`).join('');

  return {
    id: generateId(),
    title: 'Conversations',
    type: 'conversations',
    content: `
<section class="chapter">
  <h2 class="chapter-title">Chapter 4: Conversations with Your AI Companion</h2>
  <p class="chapter-intro">The most meaningful exchanges from your reading conversations.</p>
  ${convosHtml || '<p class="empty">No conversations recorded.</p>'}
</section>`,
    data: { count: conversations.conversations.length },
  };
}

function renderSynthesis(synthesis: EnrichedSynthesis): PersonalBookSection {
  const insightsHtml = synthesis.insights.map((i) => `
    <div class="insight">
      <h3 class="insight-theme">${esc(i.theme)}</h3>
      <p>${esc(i.description)}</p>
    </div>`).join('');

  const connectionsHtml = synthesis.connections.map((c) => `
    <div class="connection">
      <span class="connection-book">${esc(c.title)} by ${esc(c.author)}</span>
      <p>${esc(c.connection)}</p>
    </div>`).join('');

  return {
    id: generateId(),
    title: 'What You Discovered',
    type: 'insights',
    content: `
<section class="chapter">
  <h2 class="chapter-title">Chapter 5: What You Discovered</h2>
  <div class="insights">
    ${insightsHtml || '<p class="empty">Keep reading and highlighting to discover insights.</p>'}
  </div>
  ${connectionsHtml ? `<h3 class="sub-title">Connections Across Your Library</h3><div class="connections">${connectionsHtml}</div>` : ''}
</section>`,
    data: { insights: synthesis.insights, connections: synthesis.connections },
  };
}

function renderForward(synthesis: EnrichedSynthesis): PersonalBookSection {
  const recsHtml = synthesis.recommendations.map((r) => `<li>${esc(r)}</li>`).join('');
  const questionsHtml = synthesis.unresolvedQuestions.map((q) => `
    <div class="question">
      <p class="question-text">${esc(q.question)}</p>
      ${q.context ? `<p class="question-context">${esc(q.context)}</p>` : ''}
    </div>`).join('');

  return {
    id: generateId(),
    title: 'Looking Forward',
    type: 'forward',
    content: `
<section class="chapter">
  <h2 class="chapter-title">Chapter 6: Looking Forward</h2>
  ${synthesis.recommendations.length > 0 ? `
    <h3 class="sub-title">Recommended Next Reads</h3>
    <ul class="recommendations">${recsHtml}</ul>
  ` : ''}
  ${questionsHtml ? `
    <h3 class="sub-title">Unresolved Questions</h3>
    <div class="questions">${questionsHtml}</div>
  ` : ''}
  <div class="reflection">
    <h3 class="sub-title">A Moment of Reflection</h3>
    <blockquote class="reflection-prompt">${esc(synthesis.reflectionPrompt)}</blockquote>
  </div>
</section>`,
    data: { recommendations: synthesis.recommendations },
  };
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric', month: 'short', day: 'numeric',
    });
  } catch {
    return iso;
  }
}

// ---------------------------------------------------------------------------
// CSS Styles
// ---------------------------------------------------------------------------

const STYLES = `
@import url('https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700&display=swap');

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --color-bg: #faf7f2;
  --color-paper: #fffdf8;
  --color-text: #2c2416;
  --color-heading: #3d2b14;
  --color-muted: #7a6b52;
  --color-light: #9b8b6e;
  --color-accent: #b8860b;
  --color-accent-light: #d4a574;
  --color-highlight-bg: #f5ede0;
  --color-highlight-border: #d4a574;
  --font-serif: 'Merriweather', Georgia, 'Palatino Linotype', 'Book Antiqua', serif;
  --font-body: 'Merriweather', Georgia, serif;
}

body {
  font-family: var(--font-body);
  background: var(--color-bg);
  color: var(--color-text);
  line-height: 1.8;
  padding: 2rem;
  -webkit-font-smoothing: antialiased;
}

.book {
  max-width: 720px;
  margin: 0 auto;
  background: var(--color-paper);
  padding: 2rem 3rem;
  box-shadow: 0 2px 40px rgba(44, 36, 22, 0.08);
  border-radius: 2px;
}

/* ── Cover ─────────────────────────────────────────────────────────────── */
.cover {
  text-align: center;
  padding: 5rem 2rem 4rem;
  margin-bottom: 2rem;
  position: relative;
}
.cover::after {
  content: '';
  display: block;
  width: 40%;
  max-width: 200px;
  height: 1px;
  background: linear-gradient(to right, transparent, var(--color-accent-light), transparent);
  margin: 3rem auto 0;
}
.cover-inner { max-width: 480px; margin: 0 auto; }
.cover-image {
  max-width: 180px;
  border-radius: 4px;
  margin-bottom: 2rem;
  box-shadow: 0 6px 30px rgba(0,0,0,0.12), 0 1px 4px rgba(0,0,0,0.06);
}
.cover-title {
  font-family: var(--font-serif);
  font-size: 2.4rem;
  font-weight: 900;
  color: var(--color-heading);
  line-height: 1.25;
  margin-bottom: 0.5rem;
  letter-spacing: -0.02em;
}
.cover-author {
  font-size: 1.15rem;
  color: var(--color-muted);
  font-style: italic;
  margin-bottom: 2rem;
}
.cover-ornament {
  font-size: 1.5rem;
  color: var(--color-accent-light);
  letter-spacing: 0.5em;
  margin: 1.5rem 0;
}
.cover-subtitle {
  font-family: var(--font-serif);
  font-size: 1.25rem;
  color: var(--color-accent);
  font-style: italic;
  line-height: 1.5;
  margin-bottom: 2rem;
}
.cover-reader { font-size: 1rem; color: var(--color-text); }
.cover-meta { font-size: 0.85rem; color: var(--color-light); margin-top: 0.5rem; }
.cover-badge {
  display: inline-block;
  margin-top: 1.5rem;
  padding: 0.4rem 1.2rem;
  border: 1px solid var(--color-accent-light);
  border-radius: 2px;
  font-size: 0.7rem;
  color: var(--color-accent);
  text-transform: uppercase;
  letter-spacing: 0.15em;
}

/* ── Chapters ──────────────────────────────────────────────────────────── */
.chapter {
  padding: 2.5rem 0 2rem;
  position: relative;
}
.chapter + .chapter::before {
  content: '\\2727';
  display: block;
  text-align: center;
  font-size: 1.2rem;
  color: var(--color-accent-light);
  margin-bottom: 2rem;
  letter-spacing: 0.5em;
}
.chapter-title {
  font-family: var(--font-serif);
  font-size: 1.45rem;
  font-weight: 700;
  color: var(--color-heading);
  margin-bottom: 0.75rem;
  letter-spacing: -0.01em;
}
.chapter-intro {
  font-size: 0.95rem;
  color: var(--color-muted);
  font-style: italic;
  margin-bottom: 1.75rem;
  line-height: 1.7;
}
.sub-title {
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--color-heading);
  margin: 2rem 0 0.75rem;
  padding-bottom: 0.3rem;
  border-bottom: 1px solid #e8dcc8;
}

/* ── Timeline ──────────────────────────────────────────────────────────── */
.timeline { padding-left: 1.5rem; border-left: 2px solid var(--color-accent-light); margin-left: 0.25rem; }
.milestone { position: relative; padding: 0.5rem 0 1.5rem 1.5rem; }
.milestone-dot {
  position: absolute; left: -9px; top: 8px;
  width: 16px; height: 16px; border-radius: 50%;
  background: var(--color-accent-light);
  border: 3px solid var(--color-paper);
  box-shadow: 0 0 0 1px var(--color-accent-light);
}
.milestone-dot.active { background: var(--color-accent); }
.milestone-label { font-weight: 700; color: var(--color-heading); font-size: 0.95rem; }
.milestone-date { font-size: 0.82rem; color: var(--color-light); margin-top: 0.1rem; }
.milestone-detail { font-size: 0.9rem; color: var(--color-muted); margin-top: 0.3rem; }

/* ── Themes / Highlights ───────────────────────────────────────────────── */
.theme-cluster { margin-bottom: 2.5rem; }
.theme-name {
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--color-heading);
  margin-bottom: 0.25rem;
}
.theme-desc {
  font-size: 0.9rem;
  color: var(--color-muted);
  font-style: italic;
  margin-bottom: 1rem;
}
.theme-highlights { display: flex; flex-direction: column; gap: 0.75rem; }
.highlight-ref {
  font-size: 0.93rem;
  color: var(--color-text);
  border-left: 3px solid var(--color-highlight-border);
  padding: 0.6rem 1rem;
  background: var(--color-highlight-bg);
  border-radius: 0 4px 4px 0;
  line-height: 1.65;
  position: relative;
}
.highlight-ref::before {
  content: '\\201C';
  font-size: 1.6rem;
  color: var(--color-accent-light);
  position: absolute;
  top: -0.1rem;
  left: 0.3rem;
  opacity: 0.5;
  font-family: Georgia, serif;
}
.highlight-ref > *:first-child { margin-top: 0; }
.highlight-note {
  display: block;
  font-size: 0.85rem;
  color: var(--color-muted);
  font-style: italic;
  margin-top: 0.5rem;
  padding-top: 0.5rem;
  border-top: 1px dashed #e0d5c0;
}

/* ── Notes ─────────────────────────────────────────────────────────────── */
.tag-cloud { margin-bottom: 1.75rem; line-height: 2.2; }
.tag {
  display: inline-block;
  padding: 3px 10px;
  margin: 2px;
  background: #f0e4cc;
  border-radius: 14px;
  font-size: 0.78rem;
  color: var(--color-muted);
  font-weight: 600;
}
.note-entry {
  margin-bottom: 1.25rem;
  padding: 1rem 1.25rem;
  background: var(--color-highlight-bg);
  border-radius: 4px;
  border-left: 3px solid var(--color-accent-light);
}
.note-chapter {
  font-size: 0.72rem;
  color: var(--color-light);
  text-transform: uppercase;
  letter-spacing: 0.08em;
  font-weight: 700;
}
.note-quote {
  font-size: 0.88rem;
  color: var(--color-muted);
  margin: 0.5rem 0;
  border-left: 2px solid var(--color-accent-light);
  padding-left: 0.75rem;
  font-style: italic;
}
.note-text { font-size: 0.95rem; color: var(--color-text); margin-top: 0.5rem; }
.note-tags { margin-top: 0.5rem; }

/* ── Conversations ─────────────────────────────────────────────────────── */
.conversation {
  margin-bottom: 1.75rem;
  border-radius: 6px;
  overflow: hidden;
  border: 1px solid #e8dcc8;
}
.msg { padding: 0.85rem 1.1rem; }
.user-msg { background: #f0f4ee; }
.ai-msg { background: var(--color-highlight-bg); border-top: 1px solid #e8dcc8; }
.msg-role {
  font-size: 0.68rem;
  font-weight: 700;
  color: var(--color-light);
  text-transform: uppercase;
  letter-spacing: 0.1em;
  display: block;
  margin-bottom: 0.3rem;
}
.msg p { font-size: 0.93rem; line-height: 1.65; }

/* ── Insights ──────────────────────────────────────────────────────────── */
.insight {
  margin-bottom: 1.25rem;
  padding: 1rem 1.25rem;
  background: #faf5ec;
  border-radius: 4px;
  border-left: 3px solid var(--color-accent);
}
.insight-theme { font-size: 1rem; font-weight: 700; color: var(--color-heading); margin-bottom: 0.25rem; }
.insight p { font-size: 0.93rem; color: var(--color-muted); }
.connection { margin-bottom: 1.25rem; padding: 0.75rem 1rem; background: #faf5ec; border-radius: 4px; }
.connection-book { font-weight: 700; color: var(--color-heading); font-size: 0.95rem; }

/* ── Forward ───────────────────────────────────────────────────────────── */
.recommendations { padding-left: 1.5rem; margin-bottom: 1.5rem; }
.recommendations li {
  margin-bottom: 0.6rem;
  font-size: 0.93rem;
  line-height: 1.6;
}
.recommendations li::marker { color: var(--color-accent-light); }
.question {
  margin-bottom: 1rem;
  padding: 0.85rem 1rem;
  background: #faf5ec;
  border-radius: 4px;
  border-left: 3px solid var(--color-accent-light);
}
.question-text { font-weight: 700; color: var(--color-heading); font-size: 0.95rem; }
.question-context { font-size: 0.85rem; color: var(--color-muted); margin-top: 0.35rem; font-style: italic; }
.reflection {
  margin-top: 2.5rem;
  padding: 2rem;
  background: linear-gradient(135deg, #f5ede0 0%, #faf5ec 100%);
  border-radius: 6px;
  text-align: center;
  border: 1px solid #e8dcc8;
}
.reflection::before {
  content: '\\2727';
  display: block;
  font-size: 1rem;
  color: var(--color-accent-light);
  margin-bottom: 1rem;
  letter-spacing: 0.5em;
}
.reflection-prompt {
  font-family: var(--font-serif);
  font-size: 1.15rem;
  font-style: italic;
  color: var(--color-heading);
  border: none;
  padding: 0;
  line-height: 1.6;
}

.empty {
  font-size: 0.95rem;
  color: var(--color-light);
  font-style: italic;
  padding: 2.5rem 0;
  text-align: center;
}

/* ── Footer ────────────────────────────────────────────────────────────── */
.book-footer {
  text-align: center;
  padding: 2rem 0 1rem;
  margin-top: 2rem;
  border-top: 1px solid #e8dcc8;
  font-size: 0.78rem;
  color: var(--color-light);
}
.book-footer::before {
  content: '\\2727';
  display: block;
  font-size: 0.9rem;
  letter-spacing: 0.5em;
  margin-bottom: 0.5rem;
}

/* ── Print ─────────────────────────────────────────────────────────────── */
@media print {
  @page {
    size: A4;
    margin: 2.5cm 2cm 2.5cm 2.5cm;
  }
  body {
    background: white;
    padding: 0;
    font-size: 11pt;
  }
  .book {
    max-width: 100%;
    background: white;
    box-shadow: none;
    padding: 0;
  }
  .cover {
    page-break-after: always;
    padding: 6rem 0 4rem;
  }
  .chapter {
    page-break-before: always;
    padding-top: 0;
  }
  .chapter:first-of-type { page-break-before: auto; }
  .chapter + .chapter::before { margin-bottom: 1rem; }
  .theme-cluster, .conversation, .insight, .note-entry, .question, .milestone {
    page-break-inside: avoid;
  }
  .cover-ornament, .cover-badge { color: #999; border-color: #ccc; }
  a { color: inherit; text-decoration: none; }
  .book-footer { display: none; }
}
`;
