#!/usr/bin/env bash
# setup-vps.sh — One-shot Docker provisioning for read-pal on Ubuntu 22.04/24.04
# Usage: ssh -i ~/.ssh/key ubuntu@HOST 'bash -s' < scripts/setup-vps.sh
set -euo pipefail

DEPLOY_DIR="/home/ubuntu/read-pal"
DB_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)

echo "=== read-pal Docker Setup ==="
echo "Deploy dir: $DEPLOY_DIR"

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
echo ">>> Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq curl git ca-certificates gnupg >/dev/null

# ---------------------------------------------------------------------------
# 2. Docker + Docker Compose
# ---------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
  echo ">>> Installing Docker..."
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg 2>/dev/null
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt-get update -qq
  sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  sudo usermod -aG docker ubuntu
fi
echo "Docker: $(docker --version)"
echo "Compose: $(docker compose version)"

# ---------------------------------------------------------------------------
# 3. Clone repo
# ---------------------------------------------------------------------------
if [[ ! -d "$DEPLOY_DIR/.git" ]]; then
  echo ">>> Cloning read-pal repository..."
  git clone https://github.com/pengdd1998/read-pal.git "$DEPLOY_DIR"
else
  echo ">>> Repository already exists, pulling latest..."
  cd "$DEPLOY_DIR" && git pull origin main
fi
cd "$DEPLOY_DIR"

# ---------------------------------------------------------------------------
# 4. Write .env file
# ---------------------------------------------------------------------------
echo ">>> Writing .env..."
cat > .env << EOF
# Auto-generated by setup-vps.sh — $(date -Iseconds)
DB_NAME=readpal
DB_USER=readpal
DB_PASSWORD=$DB_PASSWORD
REDIS_URL=redis://redis:6379
GLM_API_KEY=PLACEHOLDER_CHANGE_ME
GLM_BASE_URL=https://open.bigmodel.cn/api/paas/v4
DEFAULT_MODEL=glm-4.7-flash
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
APP_ENV=production
FRONTEND_URL=http://$(hostname -I | awk '{print $1}')
EOF
chmod 600 .env

echo ""
echo "  ⚠️  IMPORTANT: Edit .env and set GLM_API_KEY"
echo ""

# ---------------------------------------------------------------------------
# 5. Stop old PM2 / bare-metal services (if any)
# ---------------------------------------------------------------------------
echo ">>> Stopping old services..."
pm2 delete read-pal-api 2>/dev/null || true
pm2 delete read-pal-web 2>/dev/null || true
sudo systemctl stop gohttpserver 2>/dev/null || true
sudo systemctl disable gohttpserver 2>/dev/null || true

# ---------------------------------------------------------------------------
# 6. Build and start Docker Compose
# ---------------------------------------------------------------------------
echo ">>> Building and starting containers..."
docker compose up -d --build

echo ">>> Running database migrations..."
sleep 10
docker compose exec -T api python -m alembic upgrade head || echo "Migration may have already run"

# ---------------------------------------------------------------------------
# 7. Verify
# ---------------------------------------------------------------------------
echo ""
echo "=== Waiting for services to start..."
sleep 10

SERVER_IP=$(hostname -I | awk '{print $1}')
API_STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost/api/v1/health 2>/dev/null || echo "000")
WEB_STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://localhost 2>/dev/null || echo "000")

echo ""
echo "=== Setup Complete ==="
echo "  API  health: http://$SERVER_IP/api/v1/health → $API_STATUS"
echo "  Web  status:  http://$SERVER_IP/ → $WEB_STATUS"
echo "  Containers:"
docker compose ps
echo ""
echo "  ⚠️  REMINDER: Set GLM_API_KEY in $DEPLOY_DIR/.env"
echo "  Then run: cd $DEPLOY_DIR && docker compose up -d"
echo ""
if [[ "$API_STATUS" == "200" ]]; then
  echo "  ✅ API is healthy"
else
  echo "  ❌ API returned $API_STATUS — check: docker compose logs api"
fi
if [[ "$WEB_STATUS" == "200" ]]; then
  echo "  ✅ Web is healthy"
else
  echo "  ❌ Web returned $WEB_STATUS — check: docker compose logs web"
fi
